---
COMMON: &common
  SECRET_KEY: 'secret'
  SQLALCHEMY_DATABASE_URI: 'sqlite:///db.sqlite'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  API_SERVER: 'ordbok_env_config_API_SERVER'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
